### ISSUE TITLE
希望可以设置开机自启

### ISSUE THREAD

**Issue by ByePastHub** [clipboard-sync/client-desktop#4]
每次都要手动启动软件，有点费时间

**Comment by mscststs** [comment]
建议手动添加到自启，如果要软件来操作的话，会申请到不必要的高权限。

1. 右键点击【开始菜单】 - 打开【运行】
2. 在窗口中输入【shell:startup】点击【确定】
3. 点击后将出现启动文件夹
4. 将程序的快捷方式复制到文件夹中即可
